# SPDX-FileCopyrightText: 2023 The ReGreet Authors
#
# SPDX-License-Identifier: 0BSD

# Create the log and state directories.
d /var/log/regreet 0755 greeter greeter - -
d /var/lib/regreet 0755 greeter greeter - -
