# SPDX-FileCopyrightText: 2022 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install GTK4
      run: sudo apt update && sudo apt install libgtk-4-dev build-essential
    - run: rustup toolchain install 1.75 --profile minimal
    - name: Restore build cache
      uses: Swatinem/rust-cache@v2.7.5

    - run: cargo build --verbose
    - run: cargo test --verbose

    - name: pre-commit
      uses: pre-commit/action@v3.0.1
    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()
